import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import api from './api/client';
import './style.css';

const roles = { ADMIN: 'Administrator', MANAGEMENT: 'Library Management', USER: 'Reader' };

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('user') || 'null'));
  if (!user) return <Auth onLogin={setUser} />;
  return <LibraryShell user={user} onLogout={() => { localStorage.clear(); setUser(null); }} />;
}

function Auth({ onLogin }) {
  const [mode, setMode] = useState('login');
  const [form, setForm] = useState({ email: 'admin@library.local', password: 'admin123', name: '', phone: '' });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async e => { e.preventDefault(); setError(''); setBusy(true); try {
    if (mode === 'register') { await api.post('/auth/register', { name: form.name, email: form.email, phone: form.phone, password: form.password }); setMode('login'); setForm({ ...form, password: 'user123' }); }
    else { const r = await api.post('/auth/login', { email: form.email, password: form.password }); localStorage.setItem('token', r.data.token); localStorage.setItem('user', JSON.stringify(r.data.user)); onLogin(r.data.user); }
  } catch (x) { setError(x.response?.data?.message || 'Something went wrong. Check that the backend is running.'); } finally { setBusy(false); } };
  return <div className="auth-page"><div className="auth-brand"><div className="brand-mark">L</div><h1>The Ledger</h1><p>A modern library, built for readers and librarians.</p><div className="auth-features"><span>📚 Physical circulation</span><span>💻 Digital reading</span><span>🤖 AI book assistant</span></div></div>
    <form className="auth-card" onSubmit={submit}><div className="eyebrow">LIBRARY PORTAL</div><h2>{mode === 'login' ? 'Welcome back' : 'Create reader account'}</h2><p className="muted">{mode === 'login' ? 'Sign in to continue to your library.' : 'Register as a reader to browse and read online.'}</p>
      {mode === 'register' && <Field label="Full name"><input value={form.name} required onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name" /></Field>}
      <Field label="Email"><input type="email" value={form.email} required onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com" /></Field>
      {mode === 'register' && <Field label="Phone"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Optional" /></Field>}
      <Field label="Password"><input type="password" value={form.password} required onChange={e=>setForm({...form,password:e.target.value})} /></Field>
      {error && <div className="alert error">{error}</div>}<button className="primary wide" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in →' : 'Create account'}</button>
      <div className="auth-switch">{mode === 'login' ? <>New reader? <button type="button" onClick={()=>setMode('register')}>Register</button></> : <>Already registered? <button type="button" onClick={()=>setMode('login')}>Sign in</button></>}</div>
      {mode === 'login' && <div className="demo-box"><b>Demo accounts</b><span>Admin: admin@library.local / admin123</span><span>Management: manager@library.local / manager123</span><span>Reader: user@library.local / user123</span></div>}
    </form></div>;
}

function LibraryShell({ user, onLogout }) {
  const staff = user.role === 'ADMIN' || user.role === 'MANAGEMENT';
  const [page, setPage] = useState('overview');
  const [books, setBooks] = useState([]), [issues, setIssues] = useState([]), [users, setUsers] = useState([]), [dash, setDash] = useState(null);
  const [notice, setNotice] = useState('');
  const loadBooks = async (q='') => { const r = await api.get('/books', { params: { q } }); setBooks(r.data); };
  const load = async () => { try { await loadBooks(); if (staff) { setDash((await api.get('/dashboard')).data); setIssues((await api.get('/issues')).data); } else setIssues((await api.get('/issues/me')).data); if (user.role==='ADMIN') setUsers((await api.get('/users')).data); } catch (e) { setNotice(e.response?.data?.message || 'Unable to load data.'); } };
  useEffect(()=>{load()},[user.role]);
  const nav = [
    ['overview','⌂','Overview'], ['catalog','▦','Catalog'], ['online','◉','Online Reading'], ['ai','✦','AI Assistant'], ['mybooks','▤',staff?'Circulation':'My Books'],
    ...(staff ? [['dashboard','◫','Dashboard']] : []), ...(user.role==='ADMIN' ? [['users','♙','Users']] : []), ...(user.role==='ADMIN' ? [['onboard','＋','Onboard Book']] : [])
  ];
  const title = nav.find(n=>n[0]===page)?.[2] || 'Library';
  return <div className="app"><aside><div className="side-brand"><div className="brand-mark small">L</div><div><b>The Ledger</b><small>Library OS</small></div></div><div className="role-chip">{user.role} · {roles[user.role]}</div><nav className="side-nav">{nav.map(n=><button key={n[0]} className={page===n[0]?'active':''} onClick={()=>setPage(n[0])}><span>{n[1]}</span>{n[2]}</button>)}</nav><div className="side-bottom"><div className="profile"><div className="avatar">{user.name?.[0]?.toUpperCase()}</div><div><b>{user.name}</b><small>{user.email}</small></div></div><button className="logout" onClick={onLogout}>↪ Sign out</button></div></aside>
    <section className="content"><header className="topbar"><div><span className="eyebrow">LIBRARY PORTAL</span><h1>{title}</h1></div><div className="top-actions"><span className="status-dot">● System online</span><button className="icon-btn" onClick={load}>↻</button></div></header>{notice&&<div className="toast" onClick={()=>setNotice('')}>{notice} ×</div>}<main>
      {page==='overview' && <Overview user={user} dash={dash} issues={issues} books={books} go={setPage} />}
      {page==='catalog' && <Catalog books={books} refresh={loadBooks} staff={staff} onIssued={load} />}
      {page==='online' && <OnlineReading />}
      {page==='ai' && <AIAssistant />}
      {page==='mybooks' && <Circulation user={user} issues={issues} books={books} staff={staff} users={users} refresh={load} />}
      {page==='dashboard' && <Dashboard dash={dash} issues={issues} />}
      {page==='users' && <Users users={users} refresh={load} />}
      {page==='onboard' && <Onboard refresh={()=>{load();setPage('catalog')}} />}
    </main></section></div>;
}

function Overview({ user, dash, issues, books, go }) { const active = issues.filter(i=>i.status==='ISSUED').length; const dueSoon = issues.filter(i=>i.status==='ISSUED' && daysUntil(i.dueDate)<=2 && daysUntil(i.dueDate)>=0).length; return <>
  <div className="hero"><div><span className="eyebrow">GOOD {new Date().getHours()<12?'MORNING':new Date().getHours()<18?'AFTERNOON':'EVENING'}, {user.name?.split(' ')[0]?.toUpperCase()}</span><h2>Your library at a glance.</h2><p>Discover books, manage circulation, and keep every reader on track.</p><div className="hero-actions"><button className="primary" onClick={()=>go('catalog')}>Explore catalog →</button><button className="ghost" onClick={()=>go('ai')}>Ask Library AI ✦</button></div></div><div className="hero-book"><span>FEATURED</span><b>Read. Learn.<br/>Repeat.</b><small>One library for every format.</small></div></div>
  <div className="stat-grid">{user.role==='USER'?<><Stat label="My active loans" value={active} icon="▤" /><Stat label="Due in 2 days" value={dueSoon} icon="◷" /><Stat label="Books in catalog" value={books.length} icon="▦" /><Stat label="Online titles" value="∞" icon="◉" /></>:<><Stat label="Registered users" value={dash?.users??'—'} icon="♙" /><Stat label="Book titles" value={dash?.titles??'—'} icon="▦" /><Stat label="Books issued" value={dash?.issued??'—'} icon="▤" /><Stat label="Available copies" value={dash?.availableCopies??'—'} icon="✓" /></>}</div>
  <div className="section-head"><div><span className="eyebrow">QUICK ACCESS</span><h3>Library workspace</h3></div></div><div className="quick-grid"><Quick icon="▦" title="Browse catalog" text="Search titles, authors and availability." onClick={()=>go('catalog')} /><Quick icon="◉" title="Online reading" text="Open digital books available to readers." onClick={()=>go('online')} /><Quick icon="✦" title="Ask Library AI" text="Find availability or ask about a book." onClick={()=>go('ai')} />{user.role!=='USER'&&<Quick icon="↔" title="Circulation" text="Issue and return physical books." onClick={()=>go('mybooks')} />}</div>
  </> }
function Stat({label,value,icon}){return <div className="stat-card"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Quick({icon,title,text,onClick}){return <button className="quick" onClick={onClick}><span className="quick-icon">{icon}</span><span><b>{title}</b><small>{text}</small></span><em>→</em></button>}

function Catalog({books,refresh,staff,onIssued}) { const [q,setQ]=useState(''); const [selected,setSelected]=useState(null); const search=async e=>{e?.preventDefault();refresh(q)}; return <><div className="toolbar"><div><span className="eyebrow">COLLECTION</span><h2>Book catalog</h2><p className="muted">{books.length} titles in your current results.</p></div><form className="search" onSubmit={search}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title or author…"/><button>Search</button></form></div><div className="book-grid">{books.map(b=><BookCard key={b.id} book={b} staff={staff} onIssue={()=>setSelected(b)} onRead={()=>setSelected({...b,read:true})}/>)}</div>{!books.length&&<Empty title="No books found" text="Try another title or author." />}{selected&&!selected.read&&<IssueModal book={selected} close={()=>setSelected(null)} done={()=>{setSelected(null);onIssued()}}/>}{selected?.read&&<Reader book={selected} close={()=>setSelected(null)}/>}</> }
function BookCard({book,staff,onIssue,onRead}){return <article className="book-card"><div className="cover"><span>{book.category||'BOOK'}</span><b>{initials(book.title)}</b><small>{book.author}</small></div><div className="book-info"><div className="book-title"><h3>{book.title}</h3><span className={book.availableCopies?'badge green':'badge red'}>{book.availableCopies?'Available':'Unavailable'}</span></div><p className="muted">{book.author} · {book.isbn||'No ISBN'}</p><p className="desc">{book.description||'A title from the library collection.'}</p><div className="book-meta"><span>▣ {book.availableCopies}/{book.totalCopies} copies</span>{book.onlineAvailable&&<span>◉ Online</span>}</div><div className="card-actions">{book.onlineAvailable&&<button className="ghost" onClick={onRead}>Read online</button>}{staff&&<button className="primary" disabled={!book.availableCopies} onClick={onIssue}>Issue book</button>}</div></div></article>}

function IssueModal({book,close,done}){const [userId,setUserId]=useState(''),[email,setEmail]=useState(''),[days,setDays]=useState(14),[users,setUsers]=useState([]),[error,setError]=useState('');useEffect(()=>{api.get('/users').then(r=>setUsers(Array.isArray(r.data)?r.data:[])).catch(()=>setUsers([]))},[]);const selectableUsers = users.filter(u => u && (u.id || u.email || u.name));const submit=async e=>{e.preventDefault();if(!userId||!email){setError('Please select a valid reader.');return;}try{await api.post('/issues',{userId:Number(userId),email,bookId:book.id,days:Number(days)});done()}catch(x){setError(x.response?.data?.message||'Could not issue book')}};return <Modal title="Issue physical book" close={close}><div className="modal-book"><div className="mini-cover">{initials(book.title)}</div><div><b>{book.title}</b><span>{book.author}</span><small>{book.availableCopies} copy/copies available</small></div></div><form onSubmit={submit}><Field label="Reader"><select required value={userId} onChange={e=>{const selected = selectableUsers.find(u => String(u.id) === e.target.value); setUserId(e.target.value); setEmail(selected?.email || '');}}><option value="">Select registered reader</option>{selectableUsers.map(u=><option value={u.id} key={u.id}>{`#${u.id} · ${u.name || 'Reader'} · ${u.email || 'No email'}`}</option>)}</select></Field><Field label="Loan period"><select value={days} onChange={e=>setDays(e.target.value)}><option value="7">7 days</option><option value="14">14 days</option><option value="21">21 days</option><option value="30">30 days</option></select></Field>{error&&<div className="alert error">{error}</div>}<button className="primary wide">Confirm issue</button></form></Modal>}

function Circulation({user,issues,books,staff,users,refresh}){return <><div className="toolbar"><div><span className="eyebrow">{staff?'CIRCULATION DESK':'YOUR LOANS'}</span><h2>{staff?'Issue & return':'My books'}</h2><p className="muted">{staff?'Manage every physical loan from one place.':'Keep track of your active loans and due dates.'}</p></div></div>{staff&&<div className="notice-banner">⏱ Reminder policy: readers are notified 2 days before their due date. Late returns incur the configured daily fine.</div>}<IssueTable issues={issues} staff={staff} refresh={refresh}/></>}
function IssueTable({issues,staff,refresh}){return <div className="panel table-wrap"><table><thead><tr><th>Book</th><th>Reader</th><th>Issued</th><th>Due</th><th>Status</th><th>Fine</th>{staff&&<th></th>}</tr></thead><tbody>{issues.map(i=><tr key={i.id}><td><b>{i.book?.title}</b><small>{i.book?.author}</small></td><td>{i.user?.name}<small>{i.user?.email}</small></td><td>{fmt(i.issuedAt)}</td><td><Due date={i.dueDate} /></td><td><span className={`badge ${i.status==='ISSUED'?'blue':'green'}`}>{i.status}</span></td><td>₹{i.fine||0}</td>{staff&&<td>{i.status==='ISSUED'&&<button className="small-btn" onClick={async()=>{await api.post(`/issues/${i.id}/return`);refresh()}}>Return</button>}</td>}</tr>)}</tbody></table>{!issues.length&&<Empty title="No active loans" text="Issued books will appear here."/>}</div>}
function Due({date}){const d=daysUntil(date);return <span className={d<0?'late':d<=2?'soon':''}>{fmt(date)}{d<0?' · overdue':d<=2?' · due soon':''}</span>}

function Dashboard({dash,issues}){const overdue=issues.filter(i=>i.status==='ISSUED'&&daysUntil(i.dueDate)<0).length;return <><div className="section-head"><div><span className="eyebrow">OPERATIONS</span><h2>Library dashboard</h2></div></div><div className="stat-grid"><Stat label="Users" value={dash?.users??0} icon="♙"/><Stat label="Titles" value={dash?.titles??0} icon="▦"/><Stat label="Issued" value={dash?.issued??0} icon="▤"/><Stat label="Overdue" value={overdue} icon="!"/></div><div className="panel"><div className="panel-head"><div><b>Who has what</b><small>Current circulation snapshot</small></div></div><IssueTable issues={issues} staff={false} refresh={()=>{}}/></div></>}

function Users({users,refresh}){const [open,setOpen]=useState(false);return <><div className="toolbar"><div><span className="eyebrow">ADMINISTRATION</span><h2>Library users</h2><p className="muted">Manage readers and staff accounts.</p></div><button className="primary" onClick={()=>setOpen(true)}>＋ Create user</button></div><div className="user-grid">{users.map(u=><div className="user-card" key={u.id}><div className="avatar large">{u.name?.[0]?.toUpperCase()}</div><div><b>{u.name}</b><span>{u.email}</span><small>{u.phone||'No phone'}</small></div><span className="badge blue">{u.role}</span></div>)}</div>{open&&<CreateUser close={()=>setOpen(false)} done={()=>{setOpen(false);refresh()}}/>}</>}
function CreateUser({close,done}){const [f,setF]=useState({name:'',email:'',phone:'',password:'user123',role:'USER'}),[error,setError]=useState('');const s=(k,v)=>setF({...f,[k]:v});const submit=async e=>{e.preventDefault();try{await api.post('/users',f);done()}catch(x){setError(x.response?.data?.message||'Could not create user')}};return <Modal title="Create account" close={close}><form onSubmit={submit}>{[['name','Full name'],['email','Email'],['phone','Phone']].map(([k,l])=><Field key={k} label={l}><input required={k!=='phone'} value={f[k]} onChange={e=>s(k,e.target.value)} /></Field>)}<Field label="Temporary password"><input value={f.password} onChange={e=>s('password',e.target.value)}/></Field><Field label="Role"><select value={f.role} onChange={e=>s('role',e.target.value)}><option>USER</option><option>MANAGEMENT</option><option>ADMIN</option></select></Field>{error&&<div className="alert error">{error}</div>}<button className="primary wide">Create account</button></form></Modal>}

function Onboard({refresh}){const [f,setF]=useState({title:'',author:'',isbn:'',category:'',description:'',totalCopies:1,onlineAvailable:false,digitalContent:''}),[saving,setSaving]=useState(false),[error,setError]=useState('');const s=(k,v)=>setF({...f,[k]:v});const submit=async e=>{e.preventDefault();setSaving(true);try{await api.post('/books',{...f,totalCopies:Number(f.totalCopies)});refresh()}catch(x){setError(x.response?.data?.message||'Could not save book')}finally{setSaving(false)}};return <div className="form-layout"><div><span className="eyebrow">ADMIN · COLLECTION</span><h2>Onboard a new book</h2><p className="muted">Add a title, physical inventory and optional digital reading content.</p><div className="tips"><b>Before publishing</b><span>✓ Verify ISBN and title</span><span>✓ Add the actual number of physical copies</span><span>✓ Only upload content you are authorized to distribute</span></div></div><form className="panel form-card" onSubmit={submit}><div className="form-grid"><Field label="Book title"><input required value={f.title} onChange={e=>s('title',e.target.value)} placeholder="e.g. Clean Code"/></Field><Field label="Author"><input required value={f.author} onChange={e=>s('author',e.target.value)} placeholder="Robert C. Martin"/></Field><Field label="ISBN"><input value={f.isbn} onChange={e=>s('isbn',e.target.value)} /></Field><Field label="Category"><input value={f.category} onChange={e=>s('category',e.target.value)} placeholder="Programming"/></Field></div><Field label="Description"><textarea value={f.description} onChange={e=>s('description',e.target.value)} /></Field><Field label="Physical copies"><input type="number" min="1" max="10000" value={f.totalCopies} onChange={e=>s('totalCopies',e.target.value)}/></Field><label className="check"><input type="checkbox" checked={f.onlineAvailable} onChange={e=>s('onlineAvailable',e.target.checked)}/><span><b>Enable online reading</b><small>Registered users can read this title online.</small></span></label>{f.onlineAvailable&&<Field label="Digital content"><textarea required value={f.digitalContent} onChange={e=>s('digitalContent',e.target.value)} placeholder="Enter licensed text/content for this demo. In production, use object storage + secure reader."/></Field>}{error&&<div className="alert error">{error}</div>}<button className="primary" disabled={saving}>{saving?'Saving…':'Publish book →'}</button></form></div>}

function OnlineReading(){const [books,setBooks]=useState([]),[q,setQ]=useState(''),[book,setBook]=useState(null);useEffect(()=>{api.get('/books/public/online').then(r=>setBooks(r.data))},[]);const filtered=books.filter(b=>(b.title+' '+b.author).toLowerCase().includes(q.toLowerCase()));return <><div className="toolbar"><div><span className="eyebrow">DIGITAL SHELF</span><h2>Online reading room</h2><p className="muted">Read the library's available digital collection.</p></div><div className="search compact"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search digital books…"/></div></div><div className="digital-grid">{filtered.map(b=><button className="digital-card" key={b.id} onClick={()=>setBook(b)}><div className="digital-cover">◉<small>DIGITAL</small></div><div><h3>{b.title}</h3><p>{b.author}</p><span>Open reader →</span></div></button>)}</div>{book&&<Reader book={book} close={()=>setBook(null)}/>}</>}
function Reader({book,close}){const [data,setData]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{api.get(`/ai/book/${book.id}/read`).then(r=>setData(r.data)).finally(()=>setLoading(false))},[book.id]);return <Modal title={book.title} close={close} wide><div className="reader"><div className="reader-head"><div><span className="eyebrow">NOW READING</span><h2>{book.title}</h2><p>{book.author}</p></div><span className="badge green">ONLINE</span></div>{loading?<p>Loading book…</p>:<div className="book-text">{data?.content?.split('\n').map((p,i)=><p key={i}>{p}</p>)}</div>}</div></Modal>}

function AIAssistant(){const [q,setQ]=useState(''),[messages,setMessages]=useState([{role:'assistant',text:`Hello ${JSON.parse(localStorage.getItem('user')||'{}').name?.split(' ')[0]||'there'}! Ask me about the library catalog.`}]),[busy,setBusy]=useState(false);const ask=async e=>{e?.preventDefault();const prompt=q.trim();if(!prompt)return;setMessages(prev=>[...prev,{role:'user',text:prompt}]);setQ('');setBusy(true);try{const r=await api.post('/ai/ask',{question:prompt});setMessages(prev=>[...prev,{role:'assistant',text:r.data.answer,provider:r.data.provider}]);}catch(x){setMessages(prev=>[...prev,{role:'assistant',text:x.response?.data?.message||'AI assistant is unavailable.'}]);}finally{setBusy(false)}};return <div className="ai-layout"><div className="ai-hero"><div className="ai-orb">✦</div><span className="eyebrow">LIBRARY AI</span><h2>Your intelligent library desk.</h2><p>Ask about availability, authors, online access, or any title in the catalog.</p><div className="suggestions">{['Is Clean Code available?','Which books can I read online?','Find books by Java authors'].map(x=><button key={x} onClick={()=>setQ(x)}>{x}</button>)}</div></div><form className="ai-panel" onSubmit={ask}><div className="chat">{messages.map((m,i)=><div key={i} className={m.role==='assistant'?'ai-message':'user-message'}><span className={m.role==='assistant'?'ai-avatar':'user-tag'}>{m.role==='assistant'?'✦':'YOU'}</span><div><b>{m.role==='assistant'?'Library AI':'You'}</b><p>{m.text}</p>{m.provider&&<small>Provider: {m.provider}</small>}</div></div>)}</div><div className="ai-input"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask: Is The Pragmatic Programmer available?"/><button className="primary" disabled={busy}>{busy?'…':'Ask ✦'}</button></div></form></div>}

function Modal({title,close,children,wide=false}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={`modal ${wide?'wide':''}`}><div className="modal-head"><h3>{title}</h3><button className="close" onClick={close}>×</button></div>{children}</div></div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Empty({title,text}){return <div className="empty"><div>▱</div><b>{title}</b><span>{text}</span></div>}
function initials(s='Book'){return s.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function fmt(x){return x?new Date(x+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'}
function daysUntil(x){return Math.ceil((new Date(x+'T00:00:00')-new Date(new Date().toDateString()))/86400000)}

createRoot(document.getElementById('root')).render(<App/>);
